import { siteConfig } from '@/config/site';
import { generatePageMetadata } from '@/lib/seo/metadata';
import Breadcrumbs from '@/components/seo/Breadcrumbs';
import Link from 'next/link';

export const metadata = generatePageMetadata({
  title: 'AI Disclaimer',
  description: 'Read the IndiaWise AI Disclaimer regarding the use, capabilities, and limitations of IndiaWise Mini AI.',
  path: '/ai-disclaimer',
});

export default function AIDisclaimerPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-8">
      <Breadcrumbs items={[{ label: 'AI Disclaimer', href: '/ai-disclaimer' }]} />

      <div className="mt-6">
        <h1 className="text-4xl font-bold text-navy mb-8">AI Disclaimer</h1>
        <p className="text-muted text-sm mb-8">Last updated: September 2026</p>

        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6 mb-10">
          <p className="text-amber-900 font-semibold text-lg mb-2">Important Notice</p>
          <p className="text-amber-800 leading-relaxed">
            IndiaWise Mini AI is an automated conversational assistant powered by artificial intelligence. All responses, explanations, and calculator guidance are strictly for general informational and educational purposes. They do NOT constitute personalized financial, investment, taxation, legal, or medical advice.
          </p>
        </div>

        <section className="space-y-4 mb-10">
          <h2 className="text-2xl font-bold text-navy">1. Nature of IndiaWise AI</h2>
          <p className="text-muted leading-relaxed">
            IndiaWise AI is built to help users navigate our platform, discover relevant calculators, interpret mathematical results, and explore hypothetical What-If financial scenarios. While calculations invoke deterministic mathematical tools, natural language explanations, summaries, and conversational responses are generated via large language model technology.
          </p>
        </section>

        <section className="space-y-4 mb-10">
          <h2 className="text-2xl font-bold text-navy">2. No Professional or Fiduciary Relationship</h2>
          <p className="text-muted leading-relaxed">
            Interacting with IndiaWise AI does not create any fiduciary, advisory, accounting, legal, or medical relationship between you and IndiaWise or its creators. IndiaWise AI is not a SEBI-registered Investment Advisor, Chartered Accountant, certified financial planner, attorney, or doctor. You should always consult with licensed, qualified professionals before executing investments, applying for loans, structuring taxes, or making health-related decisions.
          </p>
        </section>

        <section className="space-y-4 mb-10">
          <h2 className="text-2xl font-bold text-navy">3. Potential for Inaccuracies and Hallucinations</h2>
          <p className="text-muted leading-relaxed">
            Artificial intelligence systems may occasionally generate incomplete, imprecise, or outdated information (commonly known as AI hallucinations). While we implement rigorous deterministic tool validation for calculations, you must independently verify all numbers, tax slabs, bank policies, and assumptions before making financial commitments.
          </p>
        </section>

        <section className="space-y-4 mb-10">
          <h2 className="text-2xl font-bold text-navy">4. No Financial Guarantees</h2>
          <p className="text-muted leading-relaxed">
            Neither IndiaWise nor IndiaWise AI guarantees any financial outcome, interest rate, tax rebate, or investment return. Projections (such as historical mutual fund or SIP return estimates) are purely illustrative and do not predict future performance. Market-linked investments remain subject to market risks.
          </p>
        </section>

        <section className="space-y-4 mb-10">
          <h2 className="text-2xl font-bold text-navy">5. What-If Scenarios & Hypothetical Comparisons</h2>
          <p className="text-muted leading-relaxed">
            Any &quot;What-If&quot; scenarios, FD comparisons, salary projections, or loan adjustments provided by IndiaWise AI reflect hypothetical simulations based solely on user inputs. They do not automatically alter, amend, or apply to any existing contract with a real-world bank, lender, or financial institution.
          </p>
        </section>

        <section className="space-y-4 mb-10">
          <h2 className="text-2xl font-bold text-navy">6. Limitation of Liability</h2>
          <p className="text-muted leading-relaxed">
            Under no circumstances shall IndiaWise, its founder Ishan Bansal, or its contributors be held liable for any financial losses, lost profits, tax penalties, or damages arising out of your reliance on information generated by IndiaWise AI. Your use of IndiaWise AI is entirely at your own discretion and risk.
          </p>
        </section>

        <section className="space-y-4 mb-10">
          <h2 className="text-2xl font-bold text-navy">7. Ephemeral Session Privacy</h2>
          <p className="text-muted leading-relaxed">
            IndiaWise AI does not require user accounts or logins, and conversations are not permanently stored in a user database. Exiting the conversation resets the in-memory chat session. Please do not submit sensitive personal identifiers, bank account numbers, passwords, or confidential records into the chat.
          </p>
        </section>

        <section className="space-y-4 mb-10">
          <h2 className="text-2xl font-bold text-navy">8. Related Disclosures & Contact</h2>
          <p className="text-muted leading-relaxed">
            This AI Disclaimer supplements our <Link href="/disclaimer" className="text-brand hover:underline font-medium">General Disclaimer</Link>, <Link href="/terms" className="text-brand hover:underline font-medium">Terms of Use</Link>, and <Link href="/privacy-policy" className="text-brand hover:underline font-medium">Privacy Policy</Link>.
          </p>
          <p className="text-muted leading-relaxed">
            If you have questions, feedback, or need clarification regarding IndiaWise AI, reach out to us at <a href={`mailto:${siteConfig.email}`} className="text-brand hover:underline font-medium">{siteConfig.email}</a>.
          </p>
        </section>
      </div>
    </div>
  );
}
