export interface CalculatorInputOption {
  label: string;
  value: string | number;
}

export interface CalculatorInput {
  id: string;
  label: string;
  type: 'number' | 'select' | 'radio';
  placeholder?: string;
  unit?: string;
  unitOptions?: string[];
  min?: number;
  max?: number;
  step?: number;
  defaultValue: number | string;
  required?: boolean;
  isAdvanced?: boolean;
  options?: CalculatorInputOption[];
  helpText?: string;
}

export interface CalculatorResult {
  id: string;
  label: string;
  value: number | string;
  unit?: string;
  isHighlighted?: boolean;
  isCurrency?: boolean;
  description?: string;
}

export interface CalculatorFAQ {
  question: string;
  answer: string;
}

export interface WhatIfConfig {
  id: string; // The input key, e.g., 'extraPayment'
  label: string; // The label, e.g., 'Pay Extra Every Month'
  min: number;
  max: number;
  step: number;
  defaultValue: number;
  unit?: string; // e.g., '₹'
  type?: 'slider' | 'fd-compare';
}

export interface CalculatorDefinition {
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  shortDescription: string;
  longDescription: string;
  inputs: CalculatorInput[];
  keywords: string[];
  relatedCalculators?: string[];
  faqs?: CalculatorFAQ[];
  schemaType?: string;
  whatIf?: WhatIfConfig; // The configuration for the What-If slider
}

export interface AmortizationRow {
  period: number;
  openingBalance: number;
  emi: number;
  principalPaid: number;
  interestPaid: number;
  closingBalance: number;
}

export interface GrowthRow {
  period: number; // year
  invested: number;
  returns: number;
  total: number;
}

export interface CalculatorResultPayload {
  results: CalculatorResult[];
  whatIfResults?: CalculatorResult[]; // The additional results generated by the What-If scenario
  amortization?: AmortizationRow[];
  growthData?: GrowthRow[];
}

export type CalculatorFn = (inputs: Record<string, number | string>) => CalculatorResultPayload;

export interface CalculatorEntry {
  definition: CalculatorDefinition;
  calculate: CalculatorFn;
}
