import { siteConfig } from '@/config/site';
import { generatePageMetadata } from '@/lib/seo/metadata';
import Breadcrumbs from '@/components/seo/Breadcrumbs';
import Link from 'next/link';

export const metadata = generatePageMetadata({
  title: 'Terms of Use',
  description: 'Read the IndiaWise Terms of Use that govern your use of our calculators and platform.',
  path: '/terms',
});

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-8">
      <Breadcrumbs items={[{ label: 'Terms of Use', href: '/terms' }]} />

      <div className="mt-6">
        <h1 className="text-4xl font-bold text-navy mb-8">Terms of Use</h1>
        <p className="text-muted text-sm mb-8">Last updated: September 2026</p>

        <section className="space-y-4 mb-10">
          <h2 className="text-2xl font-bold text-navy">1. Acceptance of Terms</h2>
          <p className="text-muted leading-relaxed">By accessing and using IndiaWise, you accept and agree to be bound by these Terms of Use. If you do not agree, please do not use our platform.</p>
        </section>

        <section className="space-y-4 mb-10">
          <h2 className="text-2xl font-bold text-navy">2. Use of Calculators</h2>
          <p className="text-muted leading-relaxed">Our calculators are provided as informational tools for general estimation purposes only. The results generated by our calculators should not be considered as professional financial, tax, legal, or medical advice.</p>
          <p className="text-muted leading-relaxed">While we strive for accuracy, we cannot guarantee that all calculations are error-free. You should verify results with qualified professionals before making any financial or health decisions.</p>
        </section>

        <section className="space-y-4 mb-10">
          <h2 className="text-2xl font-bold text-navy">3. Intellectual Property</h2>
          <p className="text-muted leading-relaxed">All content on IndiaWise, including text, graphics, logos, and software, is the property of IndiaWise and is protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works without our express written consent.</p>
        </section>

        <section className="space-y-4 mb-10">
          <h2 className="text-2xl font-bold text-navy">4. Limitation of Liability</h2>
          <p className="text-muted leading-relaxed">IndiaWise and its creators shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of or inability to use our platform or calculators. Use the platform at your own risk.</p>
        </section>

        <section className="space-y-4 mb-10">
          <h2 className="text-2xl font-bold text-navy">5. Changes to Terms and Content</h2>
          <p className="text-muted leading-relaxed">We reserve the right to modify these Terms of Use, the calculators, the formulas, or any content on the platform at any time. We can change anything without prior notice. Your continued use of IndiaWise after any changes constitutes your acceptance of the revised terms and platform updates.</p>
        </section>

        <section className="space-y-4 mb-10">
          <h2 className="text-2xl font-bold text-navy">6. Artificial Intelligence & Automated Assistants</h2>
          <p className="text-muted leading-relaxed">IndiaWise provides an interactive AI assistant (&quot;IndiaWise Mini AI&quot;) designed to assist users with calculator navigation, understanding calculation outputs, and exploring hypothetical financial scenarios. AI-generated responses are strictly for informational purposes and do not constitute financial, investment, legal, tax, or medical advice. Use of the AI assistant is subject to our dedicated <Link href="/ai-disclaimer" className="text-brand hover:underline font-medium">AI Disclaimer</Link>.</p>
        </section>

        <section className="space-y-4 mb-10">
          <h2 className="text-2xl font-bold text-navy">7. Contact</h2>
          <p className="text-muted leading-relaxed">For questions about these Terms, please reach out to us at <a href={`mailto:${siteConfig.email}`} className="text-brand hover:underline">{siteConfig.email}</a> or visit our <Link href="/contact" className="text-brand hover:underline">Contact Page</Link>.</p>
        </section>
      </div>
    </div>
  );
}